###
POST {{host}}/api/review
Content-Type: application/json

{
  "authorId": "1626a411-7a8f-4c30-a350-eaa8b768761d",
  "crims": [ "jean", "<uk 2>" ],
  "date": "2021-08-31T01:30:00.000",
  "stars": 1,
  "text": "AGAIN???? Come one, choose someone else!!!"
}


###
GET {{host}}/api/review


###
GET {{host}}/api/review?page=0&size=10


###
GET {{host}}/api/review/alice


###
GET {{host}}/api/criminal/review/bob