###
POST {{host}}/v1/review
Content-Type: application/json

{
  "authorId": "52290734-214b-44ed-8b5b-21b967a3de0d",
  "crims": [ "jean", "<uk 2>" ],
  "date": "2021-10-05T00:21:00+00:00",
  "stars": 5,
  "text": "AGAIN???? Come one, choose someone else!!!"
}


###
GET {{host}}/v1/review


###
GET {{host}}/v1/review?page=0&size=10


###
GET {{host}}/v1/review/alice


###
GET {{host}}/v1/criminal/review/bob