POST {{host}}/api/user
Content-Type: application/json

{
  "username":  "~test~",
  "encodedPwd": "12345678"
}


###
GET {{host}}/api/user/Applin


###
POST {{host}}/login?username=Applin&password=1234qwer


###
POST {{host}}/logout
